## valid uuid = 40cc9faf-cf02-4775-aaac-0f9863ec7f58

### Create a Category
POST http://localhost:3000/categories
Content-Type: application/json

{
	"name": "Category Test 4",
	"description": "Description Test 4"
}
###
GET http://localhost:3000/categories